---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jafracon/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH 
    - /bin/cp index.html $DEPLOYPATH